/* ================================================================
   Firebase Configuration
   Using Firebase Compat SDK (v10.12.0)

   ⚠️  NO SECRETS ARE STORED HERE.
   Credentials are loaded at runtime from env-config.js, which is:
     • Generated by GitHub Actions (from GitHub Secrets) in CI/CD
     • Created manually from env-config.example.js for local dev
     • Listed in .gitignore — never committed to the repository
   ================================================================ */

// Guard: ensure env-config.js was loaded before this script
if (!window.__ENV__) {
  throw new Error(
    "[firebase-config.js] window.__ENV__ is not defined. " +
    "Make sure env-config.js is loaded BEFORE firebase-config.js in your HTML. " +
    "For local development, copy js/env-config.example.js → js/env-config.js and fill in your credentials."
  );
}

const {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
} = window.__ENV__;

// Validate that all required keys are present and non-empty
const requiredKeys = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];
const missing = requiredKeys.filter((k) => !window.__ENV__[k] || window.__ENV__[k].includes("YOUR_"));
if (missing.length > 0) {
  throw new Error(
    `[firebase-config.js] The following environment variables are missing or still set to placeholder values: ${missing.join(", ")}. ` +
    "Please update js/env-config.js with your real Firebase credentials."
  );
}

const firebaseConfig = {
  apiKey:            FIREBASE_API_KEY,
  authDomain:        FIREBASE_AUTH_DOMAIN,
  projectId:         FIREBASE_PROJECT_ID,
  storageBucket:     FIREBASE_STORAGE_BUCKET,
  messagingSenderId: FIREBASE_MESSAGING_SENDER_ID,
  appId:             FIREBASE_APP_ID,
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

// Initialize services
const auth = firebase.auth();
const db = firebase.firestore();

// Configure auth persistence - keep user logged in across browser sessions
auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL)
  .catch((error) => {
    console.error("Auth persistence error:", error);
  });

// Make globally available
window.auth = auth;
window.db = db;

console.log("%c🔒 SecureAuth Firebase initialized", "color: #6366f1; font-weight: bold;");
